addpath('~/Documents/MATLAB/spm12');
addpath('~/Documents/MATLAB/NIfTI_20140122')
current_dir = pwd;
test_sub_dir__6_1 = '/Volumes/coax_lab/patrick_project/subjects/subjects/0006_1/';
test_sub_dir_12_1 = '/Volumes/coax_lab/patrick_project/subjects/subjects/0012_1/';
subs_root = '/Volumes/coax_lab/patrick_project/subjects/subjects/';

pre_session = cppi_extract_session_features(test_sub_dir__6_1, subs_root, '0006');
post_session = cppi_extract_session_features(test_sub_dir_12_1, subs_root, '0012');


subject6 = Cppi_Subject( ...
              '0006', ...
              'sequence', ...
              pre_session, ...
              pre_session);
          
          
          
          
subject12 = Cppi_Subject( ...
              '0012', ...
              'control', ...
              post_session, ...
              post_session);